services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: blog-app:latest  
    container_name: blog-app
    ports:
      - "3000:3000"
    volumes:
      - ./blog-app:/blog-app
